// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import type { DefaultHomepageProps } from "./plasmic/test_123/PlasmicHomepage";
import { PlasmicHomepage } from "./plasmic/test_123/PlasmicHomepage";
import type { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Link } from "@remix-run/react";

export interface HomepageProps extends DefaultHomepageProps {
  toggle: () => void;
}

const HomepageOne = (
  { toggle, ...rest }: HomepageProps,
  ref: HTMLElementRefOf<"div">
) => {
  return (
    <PlasmicHomepage
      root={{ ref }}
      {...rest}
      logo={{
        as: Link,
        props: {
          to: "/",
          onClick: toggle,
        },
      }}
      services={{
        as: Link,
        props: {
          to: "/services",
          prefetch: "intent",
        },
      }}
      features={{
        as: Link,
        props: {
          to: "/features",
          prefetch: "intent",
        },
      }}
      company={{
        as: Link,
        props: {
          to: "/company",
          prefetch: "intent",
        },
      }}
      contact={{
        as: Link,
        props: {
          to: "/contact",
          prefetch: "intent",
        },
      }}
      login={{
        as: Link,
        props: {
          to: "/login",
          prefetch: "intent",
        },
      }}
      signup={{
        as: Link,
        props: {
          to: "/signup",
          prefetch: "intent",
        },
      }}
    />
  );
};

const HomepageTwo = (
  { toggle, ...rest }: HomepageProps,
  ref: HTMLElementRefOf<"div">
) => {
  return (
    <PlasmicHomepage
      root={{ ref }}
      logo={{ props: { href: "/", onClick: toggle } }}
      {...rest}
    />
  );
};

function Homepage_(props: HomepageProps, ref: HTMLElementRefOf<"div">) {
  const [state, setState] = React.useState(true);
  const toggle = () => setState((cur) => !cur);

  console.log("state", state);
  return state
    ? HomepageOne({ ...props, toggle }, ref)
    : HomepageTwo({ ...props, toggle }, ref);
}

const Homepage = React.forwardRef(Homepage_);
export default Homepage;
